name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Execute the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo kkiryazov
  
  ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run local
      run: npm start &
    - name: Install playwright's browsers
      run: npx playwright install
    - name: Execute the unit tests
      run: npm run test:ui

  deploy-to-render-com:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: ui-tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Deploy to render.com
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id:  ${{ secrets.UI_API_KEY }}
          api_key: ${{ secrets.RENDER_KEY }}
          clear_cache: true
          wait_deploy: true 